import { StyleOption } from './types';
import { SparklesIcon, AdjustmentsHorizontalIcon, PencilIcon, CubeTransparentIcon, PhotoIcon } from './components/icons';

export const STYLE_OPTIONS: StyleOption[] = [
  {
    id: 'studio',
    nameKey: 'styles.studio.name',
    descriptionKey: 'styles.studio.description',
    icon: SparklesIcon,
    prompt: 'A professional, clean studio photograph of the product on a seamless, solid light-colored background. The lighting should be soft and even, highlighting the product\'s details without harsh shadows. Minimalist and modern e-commerce style.',
    categoryKey: 'step2.category.fast',
  },
  {
    id: 'pro_studio',
    nameKey: 'styles.pro_studio.name',
    descriptionKey: 'styles.pro_studio.description',
    icon: SparklesIcon,
    prompt: 'A classic professional studio product photograph. The product is perfectly centered on a neutral, seamless background. The lighting is meticulously controlled to define the product\'s shape and texture, using a combination of key, fill, and backlights to create subtle depth and dimension. The image should be sharp, clean, and entirely focused on the product itself.',
    categoryKey: 'step2.category.advanced',
  },
  {
    id: 'social_lifestyle',
    nameKey: 'styles.social_lifestyle.name',
    descriptionKey: 'styles.social_lifestyle.description',
    icon: PhotoIcon,
    prompt: 'An authentic and relatable lifestyle photograph for social media. The product is shown in a real-life context, being used or enjoyed in a casual, everyday setting. The lighting is bright and natural, like sunlight coming through a window. The composition should feel spontaneous and unposed. Include contextual elements that tell a story about the product\'s role in daily life. The overall mood should be warm, inviting, and aspirational.',
    categoryKey: 'step2.category.advanced',
  },
  {
    id: 'snack_social',
    nameKey: 'styles.snack_social.name',
    descriptionKey: 'styles.snack_social.description',
    icon: SparklesIcon,
    prompt: 'A vibrant and fun social media product photograph, perfect for a snack brand. The product should be the star, placed in a clean, bright, and modern lifestyle setting like a kitchen counter. Overlay the image with playful, hand-drawn cartoon doodles, cute character illustrations related to the product, and bold, fun typography. Include elements like sparkles and action lines to create a sense of energy and deliciousness. The overall mood should be cheerful, energetic, and highly addictive.',
    categoryKey: 'step2.category.advanced',
  },
  {
    id: 'flat_lay',
    nameKey: 'styles.flat_lay.name',
    descriptionKey: 'styles.flat_lay.description',
    icon: CubeTransparentIcon,
    prompt: 'A carefully composed aesthetic flat lay photograph, shot directly from above (top-down view). The product is the centerpiece, surrounded by a curated selection of complementary props and textural elements on a clean, interesting surface (like linen, wood, or marble). The arrangement should be balanced, artistic, and tell a visual story. The lighting should be soft and even to avoid harsh shadows. Ideal for showcasing cosmetics, accessories, or stationery.',
    categoryKey: 'step2.category.advanced',
  },
  {
    id: 'dark_moody',
    nameKey: 'styles.dark_moody.name',
    descriptionKey: 'styles.dark_moody.description',
    icon: AdjustmentsHorizontalIcon,
    prompt: 'A dramatic and elegant dark and moody product photograph. The scene is set against a dark, textured background (like dark wood, slate, or velvet). The lighting is low-key and directional, using techniques like chiaroscuro to create deep shadows and bright, focused highlights that sculpt the product. The overall atmosphere should feel luxurious, mysterious, and sophisticated. Color palette should be rich and desaturated.',
    categoryKey: 'step2.category.advanced',
  },
  {
    id: 'custom',
    nameKey: 'styles.custom.name',
    descriptionKey: 'styles.custom.description',
    icon: PencilIcon,
    prompt: 'custom', // Special case handled in UI
    categoryKey: 'step2.category.creative',
  },
  {
    id: 'manual',
    nameKey: 'styles.manual.name',
    descriptionKey: 'styles.manual.description',
    icon: CubeTransparentIcon,
    prompt: 'manual', // Special case handled in UI
    categoryKey: 'step2.category.creative',
  },
    {
    id: 'reference',
    nameKey: 'styles.reference.name',
    descriptionKey: 'styles.reference.description',
    icon: PhotoIcon,
    prompt: 'reference', // Special case handled in UI
    categoryKey: 'step2.category.creative',
  },
  // --- LIBRARY PRESETS ---
  ...[
    // New Food Preset based on user image
    {
      name: 'Annotated Food Menu',
      prompt: 'A clean and modern food menu photograph. The main dish should be beautifully presented on an aesthetic kitchen table with soft, even lighting. Identify the main components of the dish. For each component, add a playful, hand-drawn arrow pointing to it, accompanied by a label written in clear, playful typography. The overall composition should be arranged like a modern food catalog page, looking clean, organized, and very appetizing.'
    },
    // New Beverage Presets based on user images
    { name: 'Natural Sunlight Lifestyle', prompt: 'A bright and airy lifestyle photograph of the product held in hand or placed on a windowsill, with natural sunlight streaming in, creating soft, beautiful highlights and a warm, inviting atmosphere. The background should be slightly blurred, suggesting a relaxed, everyday setting like a home or a bright cafe. The overall mood is authentic and refreshing.' },
    { name: 'Cozy Cafe Vibe', prompt: 'An inviting product photograph set in a cozy cafe. The product is placed on a wooden table next to a cup of freshly brewed coffee, a pastry, or some scattered coffee beans. The lighting is warm and soft, like indoor cafe lighting. The background shows a hint of a cafe environment (blurry chairs, plants). The mood is warm, comfortable, and perfect for a relaxing coffee break.' },
    { name: 'Playful Doodle Pop', prompt: 'A fun and energetic social media photograph. The product is placed in a clean, modern setting. The image is overlaid with cute, hand-drawn doodles, playful characters, and bold, fun text. Include elements like sparkles and motion lines to create a sense of excitement and deliciousness. The overall vibe is cheerful, trendy, and perfect for Instagram or TikTok.' },
    { name: 'Clean and Minimalist Props', prompt: 'A sophisticated and clean product photograph. The product is the main focus, placed on a minimalist surface like a marble slab or a wooden board. It is surrounded by a few carefully selected props like raw coffee beans, a spoonful of sugar, or a single green leaf. The lighting is soft and even, studio-quality, highlighting the product\'s details. The background is clean and neutral. The style is modern, elegant, and focused.' },
    // Existing Beverage Presets
    { name: 'Dynamic Milk Splash', prompt: 'A professional, high-speed photograph of the product suspended in mid-air against a bright, clear blue sky with a radiant sun. The product is surrounded by dynamic, frozen-motion splashes of fresh white milk. The lighting is bright and summery, highlighting the refreshing nature of the product. Clean, vibrant, and energetic commercial style.' },
    { name: 'Coffee Swirl Splash', prompt: 'A dynamic commercial photograph of the product captured in mid-air against a vibrant blue sky. Dramatic, swirling splashes of coffee and milk are frozen in motion around the product, creating a beautiful contrast. The lighting is bright and crisp, like a sunny day, making the product look delicious and refreshing. High-speed, commercial advertising style.' },
    { name: 'Liquid Vortex', prompt: 'An artistic product photograph featuring the product at the center of a circular vortex splash of milk and coffee droplets against a clear blue sky. The lighting is bright and clean, with a sun flare effect, creating a magical and refreshing feel. The composition is balanced and eye-catching. High-speed, creative advertising style.' },
    { name: 'Minimalist Splash', prompt: 'A clean and minimalist high-speed photograph of the product with a single, elegant splash of liquid (milk or coffee) next to it. The background is a solid, bright, cheerful color like pastel blue or yellow. The lighting is soft and even, studio quality, focusing entirely on the product and the beautiful shape of the splash. Modern and sophisticated.' },
    // Other Presets
    { name: 'Minimalist Zen', prompt: 'Minimalist zen style, product on a simple slate pedestal with a single blade of grass, soft diffused light.' },
    { name: 'Vibrant Pop Art', prompt: 'Pop art style, bold colors, graphic patterns in the background, hard-edged shadows, high contrast.' },
    { name: 'Rustic Farmhouse', prompt: 'Rustic farmhouse setting, product on a weathered wood table with burlap and dried flowers, warm morning light.' },
    { name: 'Cyberpunk Neon', prompt: 'Cyberpunk aesthetic, glowing neon lights, rain-slicked surfaces, futuristic props, dramatic blue and magenta lighting.' },
    { name: 'Art Deco Luxury', prompt: 'Art Deco style, geometric patterns, gold and black color scheme, luxurious fabrics like velvet, sharp and elegant lighting.' },
    { name: 'Bohemian Chic', prompt: 'Bohemian chic vibe, macrame details, pampas grass, natural textures, warm, hazy sunlight.' },
    { name: 'Industrial Loft', prompt: 'Industrial loft background, exposed brick, concrete floor, metal pipes, large windows with bright, directional light.' },
    { name: 'Surreal Dreamscape', prompt: 'Surreal dreamscape, floating objects, impossible geometry, pastel color palette, soft, ethereal glow.' },
    { name: 'Vintage 70s', prompt: '1970s vintage style, earthy tones (avocado green, orange, brown), shag carpet, retro patterns, warm, soft-focus lighting.' },
    { name: 'Gourmet Kitchen', prompt: 'Gourmet kitchen setting, marble countertop, high-end utensils, fresh ingredients scattered around, clean, bright light.' },
    { name: 'Tropical Paradise', prompt: 'Tropical paradise theme, surrounded by large palm leaves, exotic flowers, on a bamboo mat, bright, dappled sunlight.' },
    { name: 'Underwater Fantasy', prompt: 'Underwater fantasy scene, surrounded by glowing coral and gentle bubbles, light filtering from the surface, deep blue tones.' },
    { name: 'Cozy Winter', prompt: 'Cozy winter scene, on a knitted blanket next to a fireplace, with a cup of cocoa, soft, warm, flickering light.' },
    { name: 'Autumn Harvest', prompt: 'Autumn harvest theme, surrounded by pumpkins, colorful leaves, and acorns, warm, golden hour light.' },
    { name: 'Memphis Design', prompt: '1980s Memphis Design style, squiggles, geometric shapes, pastel and neon colors, playful and chaotic composition.' },
    { name: 'Sci-Fi Laboratory', prompt: 'Clean, sterile sci-fi laboratory, on a sleek metal surface with glowing vials and holographic displays, cool, clinical lighting.' },
    { name: 'Steampunk Workshop', prompt: 'Steampunk workshop, gears, cogs, copper pipes, antique gauges, warm, intricate lighting from gas lamps.' },
    { name: 'Japanese Wabi-Sabi', prompt: 'Wabi-sabi aesthetic, celebrating imperfection, on a cracked ceramic plate or rough linen, natural, indirect light.' },
    { name: 'Scandanavian Hygge', prompt: 'Scandinavian hygge style, light wood, soft textiles, minimalist decor, clean, soft, natural light.' },
    { name: 'High-Tech Carbon Fiber', prompt: 'High-tech aesthetic, product on a carbon fiber surface, with sleek lines and a minimalist feel, sharp, cool-toned LED lighting.' },
    { name: 'Forest Floor', prompt: 'Enchanted forest floor, surrounded by moss, mushrooms, and ferns, with shafts of light breaking through the canopy.' },
    { name: 'Desert Landscape', prompt: 'Expansive desert landscape at dusk, on a cracked earth surface, with cacti in the background, warm sunset colors.' },
    { name: 'Cosmic Nebula', prompt: 'Floating in a cosmic nebula, surrounded by stars and colorful gases, ethereal, multi-directional lighting.' },
    { name: 'Watercolor Splash', prompt: 'As if part of a watercolor painting, with soft color splashes and bleeding edges on a textured paper background.' },
    { name: 'Holographic Display', prompt: 'Projected as a futuristic hologram, with scan lines and a digital glow, on a dark, high-tech background.' },
    { name: 'Candy Land', prompt: 'Whimsical candy land setting, surrounded by lollipops, gumdrops, and candy canes, bright and colorful lighting.' },
    { name: 'Gothic Noir', prompt: 'Gothic noir style, deep shadows, single light source, on a dark, ornate surface, black and white with a hint of color.' },
    { name: 'Papercraft World', prompt: 'A world made of folded paper (origami), intricate paper-cut background, soft, even lighting.' },
    { name: 'Macro Detail', prompt: 'Extreme close-up, macro photography style, highlighting textures and fine details, shallow depth of field.' },
    { name: 'Splash Photography', prompt: 'High-speed splash photography, product emerging from or being hit by a splash of liquid (water, milk, paint), frozen motion.' },
    { name: 'Smoke and Fog', prompt: 'Mysterious scene with swirling smoke or fog around the product, dramatic, backlit for texture.' },
    { name: 'Beach Scene', prompt: 'On clean white sand with gentle waves in the background, bright, direct sunlight reflecting off the water.' },
    { name: 'Mountain Peak', prompt: 'On a rocky mountain peak, with a dramatic sky and clouds below, crisp, clear, high-altitude light.' },
    { name: 'Luxury Marble', prompt: 'On a pristine marble slab, with subtle veining, paired with minimalist gold accessories, clean, sophisticated lighting.' },
    { name: 'Concrete Brutalism', prompt: 'Brutalist architecture style, on a rough concrete block, sharp angles, stark shadows, harsh, direct light.' },
    { name: 'Kid\'s Playroom', prompt: 'In a child\'s playroom, surrounded by colorful wooden blocks and toys, bright, cheerful, and playful lighting.' },
    { name: 'Antique Library', prompt: 'In an old library, on a stack of leather-bound books, with a magnifying glass nearby, soft, warm light from a desk lamp.' },
    { name: 'Cinematic Action', prompt: 'Cinematic action shot, product in motion with a sense of speed, motion blur, and dramatic, high-contrast lighting.' },
    { name: 'Golden Hour Glow', prompt: 'Bathed in the warm, soft, golden light of sunset or sunrise, creating long, soft shadows.' },
    { name: 'Blue Hour Mood', prompt: 'Photographed during the blue hour (after sunset), cool, soft, ambient light, with a deep blue sky.' },
    { name: 'Top-Down Geometric', prompt: 'Top-down flat lay with a strong geometric arrangement of props and shadows.' },
    { name: 'Floating in Air', prompt: 'Product suspended or floating in mid-air, with a soft shadow cast below, clean, simple background.' },
    { name: 'Wrapped in Fabric', prompt: 'Draped or wrapped in flowing silk or satin fabric, creating elegant lines and soft textures.' },
    { name: 'On a Bed of Petals', prompt: 'Resting on a bed of fresh flower petals (e.g., roses, cherry blossoms), soft, romantic lighting.' },
    { name: 'Frozen in Ice', prompt: 'Product partially frozen inside a clear block of ice, with cracks and bubbles, cool, crisp lighting.' },
    { name: 'Urban Street Style', prompt: 'On a graffiti-covered wall or city pavement, edgy, candid, using natural city light.' },
    { name: 'Retro Diner', prompt: '1950s retro diner setting, checkered floors, neon signs, chrome details, bright, slightly artificial lighting.' },
    { name: 'Zen Garden', prompt: 'In a Japanese zen garden, with raked sand, smooth stones, and a bonsai tree, calm, balanced, natural light.' },
    { name: 'Art Gallery', prompt: 'Displayed in a minimalist art gallery, on a white pedestal, with focused track lighting.' },
    { name: 'Baking Scene', prompt: 'On a flour-dusted countertop, with rolling pins, cookie cutters, and other baking ingredients, warm, inviting light.' },
    { name: 'Jewelry Box', prompt: 'Inside a luxurious velvet-lined jewelry box, with soft, focused light to make it sparkle.' },
    { name: 'Misty Morning', prompt: 'Outdoor scene on a misty morning, with dew drops on surrounding nature, soft, diffused, cool-toned light.' },
    { name: 'Architectural Shadows', prompt: 'Using the sharp, geometric shadows cast by modern architecture as a background element.' },
    { name: 'Explosion of Powder', prompt: 'A cloud of colorful powder (like Holi festival powder) exploding around the product, frozen in time.' },
    { name: 'On a Cloud', prompt: 'Resting on a soft, fluffy cloud against a pale blue sky, dreamy and ethereal lighting.' },
    { name: 'Retro Wave', prompt: '80s retro wave style, synthwave grid landscape, neon sunset, chrome and magenta tones.' },
    { name: 'Claymation Style', prompt: 'Looks like a still from a claymation movie, everything made of modelling clay, soft, studio lighting.' },
    { name: 'Hand-drawn Sketch', prompt: 'Product is the only realistic element in a hand-drawn sketch or blueprint world.' },
    { name: 'On a Mirror Surface', prompt: 'On a mirror, creating a perfect reflection, with interesting lighting patterns or a simple background.' },
    { name: 'Infrared Photo Style', prompt: 'Simulating an infrared photograph, where foliage is white and the sky is dark, surreal and high-contrast.' },
    { name: 'Long Exposure Light Trails', prompt: 'Product is sharp, but surrounded by artistic light trails from a long exposure shot.' },
    { name: 'Deconstructed', prompt: 'Product is deconstructed, with its components neatly arranged around it, flat lay style.' },
    { name: 'Minimalist Color Block', prompt: 'On a background of two or three solid, bold color blocks, clean lines, hard shadows.' },
    { name: 'On a Pile of Coffee Beans', prompt: 'Nestled in a pile of roasted coffee beans, rich textures, warm, appetizing light.' },
    { name: 'Through a Window', prompt: 'Viewed through a window with raindrops on it, creating a soft, moody, and slightly distorted effect.' },
    { name: 'Rococo Elegance', prompt: 'Rococo style, ornate, pastel colors, gold filigree, cherubs, soft and opulent lighting.' },
    { name: 'Summer Picnic', prompt: 'On a checkered picnic blanket in a sunny park, with a basket and summer fruits, bright, happy sunlight.' },
    { name: 'Futuristic Organic', prompt: 'A blend of futuristic technology and organic shapes, flowing lines, glowing elements, bioluminescent light.' },
    { name: 'Vintage Apothecary', prompt: 'In a vintage apothecary or chemist shop, with old glass bottles, dried herbs, and wooden shelves, moody, atmospheric light.' },
    { name: 'Extreme Weather', prompt: 'Product enduring extreme weather, covered in snow, being hit by rain, or in a sandstorm.' },
    { name: 'Abstract Light Painting', prompt: 'Surrounded by abstract shapes and swirls created with light painting techniques in a dark environment.' },
    { name: 'On a Vinyl Record', prompt: 'Placed on a spinning vinyl record, capturing the sense of motion and musical vibe.' },
    { name: 'Hacker\'s Desk', prompt: 'On a cluttered hacker\'s desk at night, illuminated only by the glow of multiple computer monitors.' },
    { name: 'Monochromatic Tones', prompt: 'A monochromatic scene where the product and all props are different shades of the same color.' },
    { name: 'Crumpled Paper', prompt: 'On a backdrop of crumpled paper, creating interesting textures and shadows, single, direct light source.' },
    { name: 'In a Greenhouse', prompt: 'Inside a lush greenhouse, surrounded by exotic plants and humid air, with soft, filtered sunlight.' },
    { name: 'Bauhaus Inspired', prompt: 'Bauhaus style, focus on primary colors, geometric forms, and functionality, clean and graphic composition.' },
    { name: 'Liquid Metal', prompt: 'Surrounded by or resting in flowing, reflective liquid metal, high-tech and dynamic.'},
    { name: 'Pixel Art', prompt: 'The entire scene, including the product, is rendered in a retro pixel art style.' },
    { name: 'On a Stone Altar', prompt: 'On an ancient, moss-covered stone altar in a mysterious ruin, with dramatic, moody lighting.' },
    { name: 'Food Styling (Savory)', prompt: 'Professional savory food styling, with fresh herbs, spices, and perfect plating, appetizing light.' },
    { name: 'Food Styling (Sweet)', prompt: 'Professional sweet food styling, with chocolate drips, powdered sugar, and fresh berries, delicious lighting.' },
    { name: 'In a Bird\'s Nest', prompt: 'Carefully placed inside a delicate bird\'s nest, symbolizing care and nature.' },
    { name: 'Levitating over Water', prompt: 'Product levitating just above a perfectly still body of water, creating a clear reflection.' },
    { name: 'Shattered Glass', prompt: 'Surrounded by fragments of shattered glass or a mirror, creating a dynamic, edgy look.' },
    { name: 'Light Leak & Film Grain', prompt: 'Emulating an old film photograph with characteristic light leaks, film grain, and vintage colors.' },
    { name: 'On a Stack of Newspapers', prompt: 'On a stack of old, yellowed newspapers, creating a vintage, intellectual feel.' },
    { name: 'Isometric 3D', prompt: 'Presented in a clean, isometric 3D projection, like a graphic design element.' },
    { name: 'Op-Art Background', prompt: 'Against an optical art background that creates a dizzying, mesmerizing effect.' },
    { name: 'On a Tree Branch', prompt: 'Naturally perched on a mossy tree branch in a forest, integrated with nature.' },
    { name: 'Space Station Interior', prompt: 'Inside a sleek, white space station with a view of Earth through a window.' },
    { name: 'Film Noir', prompt: 'Classic film noir style, high contrast black and white, dramatic shadows from window blinds, mysterious mood.' },
    { name: 'In a Suitcase', prompt: 'Packed in a vintage leather suitcase, ready for an adventure, with travel-related props.' },
    { name: 'Cottagecore', prompt: 'Cottagecore aesthetic, in a rustic kitchen with fresh-baked bread, wildflowers, and checkered cloth, soft window light.' },
    { name: 'Grunge Style', prompt: '90s grunge aesthetic, distressed textures, chain-link fences, moody, desaturated colors, harsh flash photography.' },
    { name: 'On a Pool Float', prompt: 'Floating on a colorful inflatable in a bright blue swimming pool, fun, sunny, summer vibes.' },
    { name: 'Festive Holiday', prompt: 'Surrounded by festive holiday decorations, twinkling lights, and gift wrap, warm and cheerful.' },
    { name: 'Scientific Specimen', prompt: 'Presented as a scientific specimen, pinned or in a glass display case with a label, clean, even lighting.' },
    // Muslim Fashion Presets
    { name: 'Gamis Elegan Studio', prompt: 'A professional e-commerce fashion photo. A graceful Muslim woman with modest, natural makeup and elegant hijab draping models a modern gamis. The background is a seamless, solid, soft neutral color like off-white or light beige. The lighting is bright, soft, and even, showcasing the fabric\'s texture and the dress\'s flow. The pose is modest and sophisticated. The overall mood is chic, modern, and elegant.' },
    { name: 'Koko Modern Studio', prompt: 'A clean, modern e-commerce fashion photo. A handsome Muslim man, with a neat beard, models a stylish \'baju koko\' (modern Muslim shirt). He is standing against a minimalist, clean studio background with a neutral grey or white color. The lighting is crisp and clear, highlighting the details of the fabric and embroidery. The pose is confident yet humble. The overall look is sharp, contemporary, and respectable.' },
    { name: 'Syar\'i Fashion Lookbook', prompt: 'A fashion lookbook image for Syar\'i clothing. A Muslim woman with soft, modest makeup models a beautiful, flowing khimar and a wide gamis, showcasing a traditional yet modern silhouette. The setting is a minimalist studio with simple architectural elements, like an archway or a single minimalist chair. The lighting is soft and ethereal, creating a serene and graceful atmosphere. The focus is on the drapery and modest silhouette of the outfit.' },
    { name: 'Casual Hijab Street Style', prompt: 'A candid street style photograph with a modern studio twist. A stylish Muslim woman with a fresh, natural makeup look and effortless hijab styling wears a casual tunic and wide-leg pants, captured in a relaxed pose. The background is a clean, simulated urban environment like a solid colored wall with a hint of texture. The lighting is natural and bright, as if on a sunny day. The mood is effortlessly cool, relatable, and trendy.' },
    // Fashion Presets
    { name: 'High Fashion Editorial', prompt: 'A high fashion editorial photograph. The model wears avant-garde clothing with dramatic and expressive posing. The background is abstract and artistic, with bold lighting that creates strong highlights and deep shadows. The mood is powerful and unconventional.' },
    { name: 'Street Style Candid', prompt: 'A candid street style photograph. The model is captured mid-stride on a bustling city street, showcasing a trendy, everyday outfit. The lighting is natural and dynamic, as if caught in a fleeting moment. The background shows authentic city life, slightly blurred.' },
    { name: 'E-commerce On Model', prompt: 'A clean e-commerce fashion photo. A model stands against a seamless, solid light grey background. The lighting is bright, soft, and even, clearly showing the details, color, and fit of the clothing. The pose is simple and direct.' },
    { name: 'Lookbook Style', prompt: 'A cohesive fashion lookbook image. The model is in a minimalist studio with props that match a specific theme (e.g., mid-century modern). The lighting is consistent and flattering, and the pose showcases the versatility of the outfit.' },
    { name: 'Vintage Film Look', prompt: 'An atmospheric fashion photograph emulating 35mm film. The image has a soft focus, noticeable film grain, and warm, slightly faded colors. There might be subtle light leaks. The model wears vintage-inspired clothing in a nostalgic setting.' },
    { name: 'Minimalist Scandi Fashion', prompt: 'A minimalist Scandinavian fashion photo. The model wears clothes with clean lines and a neutral color palette. The background is a simple, bright architectural space with natural light pouring in. The mood is calm, clean, and effortlessly chic.' },
    { name: 'Boho Chic Field', prompt: 'A boho-chic fashion photograph set in a field of tall grass during golden hour. The model wears a flowing, bohemian-style dress. The light is warm, golden, and backlit, creating a soft, dreamy glow. The mood is free-spirited and romantic.' },
    { name: 'Dynamic Activewear', prompt: 'A dynamic activewear fashion photograph. The model is captured in an athletic pose that shows movement and flexibility. The setting is a modern, urban environment like a rooftop or a minimalist gym. The lighting is crisp and energetic, highlighting the texture of the fabric.' },
    { name: 'Luxury Haute Couture', prompt: 'A luxurious haute couture fashion photograph. The model wears an intricate, high-end garment in an opulent setting like a palace or a grand manor. The lighting is dramatic and cinematic, emphasizing the rich textures of the fabric and the exquisite details.' },
    { name: 'Classic Denim Americana', prompt: 'A classic Americana-style fashion photo. The model wears timeless denim pieces while leaning against a vintage muscle car on a desert highway. The lighting is bright, harsh sunlight, creating a rugged and cool vibe.' },
    { name: 'Tropical Swimwear', prompt: 'A vibrant swimwear photograph on a pristine tropical beach. The model poses by the turquoise water, with clean white sand. The lighting is bright, direct sunlight that makes the colors of the swimwear pop. The mood is sunny, confident, and carefree.' },
    { name: 'Elegant Formal Wear', prompt: 'An elegant formal wear fashion photograph. The model wears a sophisticated gown or tuxedo on a grand staircase or in a richly decorated ballroom. The lighting is soft yet dramatic, like evening light from chandeliers, creating a glamorous and refined atmosphere.' },
    { name: 'Pastel Dream Fashion', prompt: 'A soft and dreamy fashion photograph with a pastel color palette. The model is surrounded by a whimsical set made of pastel-colored blocks or fabrics. The lighting is diffused and ethereal, creating a light, airy, and fantasy-like mood.' },
    { name: 'Urban Grunge Fashion', prompt: 'An edgy, 90s grunge-inspired fashion photograph. The model wears layered, distressed clothing against a gritty urban background with graffiti or a chain-link fence. The lighting is moody and high-contrast, possibly using a harsh on-camera flash.' },
    { name: 'Corporate Business Wear', prompt: 'A sharp and professional business wear fashion photo. The model wears a modern suit in a sleek, contemporary office setting with large windows and a city view. The lighting is clean and bright, conveying confidence and power.' },
    { name: 'Accessory Focus Closeup', prompt: 'A detailed close-up shot focusing on a fashion accessory (like a watch, handbag, or necklace). The product is the sharpest point in the image, with a shallow depth of field blurring the model and background. Lighting is precise to highlight the material and craftsmanship.' },
    { name: 'Color Block Studio Fashion', prompt: 'A bold and graphic fashion photograph in a studio. The model poses against a background composed of large, solid blocks of vibrant, contrasting colors. The lighting is hard and clean, creating defined shadows for a pop-art inspired look.' },
    { name: 'Travel Vacation Style', prompt: 'A travel-themed fashion photograph. The model showcases resort wear in a beautiful, scenic location like Santorini or a bustling Moroccan market. The natural light of the location is used to create an authentic and aspirational vacation vibe.' },
    { name: 'Gender Neutral Fashion', prompt: 'A modern, androgynous fashion photograph. The focus is on strong silhouettes, tailored lines, and gender-neutral clothing. The background is minimalist and architectural, and the lighting is clean and sculptural.' },
    { name: 'Studio Portrait with Flowers', prompt: 'An artistic studio fashion portrait where the model is intertwined with or surrounded by an abundance of fresh, beautiful flowers. The lighting is soft and romantic, like a renaissance painting. The mood is artistic, delicate, and beautiful.' }
  ].map(item => {
    const key = item.name.toLowerCase().replace(/[()'&]/g, '').replace(/\s+/g, '_');
    return {
      id: `preset_${key}`,
      nameKey: `presets.${key}.name`,
      descriptionKey: `presets.${key}.description`,
      prompt: item.prompt,
      icon: SparklesIcon,
      categoryKey: 'step2.category.library',
    };
  }),
];